quarkus:
  profile:
    parent: env

  http:
    port: ${PORT}

  mongodb:
    connection-string: ${LOCAL_MONGO_URL}
    database: ${LOCAL_MONGO_DB}
    authentication-database: ${LOCAL_MONGO_AUTH_DB}
    username:
    password:

  log:
    category:
      "io.smallrye.faulttolerance": INFO

kafka:
  bootstrap:
    servers: ${LOCAL_BROKER}

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO

mp:
  messaging:
    incoming:
      created:
        connector: smallrye-kafka
        topic: "item-created"
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
