quarkus:
  profile:
    parent: env

  http:
    port: ${PORT}

  mongodb:
    connection-string: ${LOCAL_MONGO_URL}
    database: ${LOCAL_MONGO_DB}
    authentication-database: ${LOCAL_MONGO_AUTH_DB}
    username:
    password:

  log:
    category:
      "io.smallrye.faulttolerance": INFO

kafka:
  bootstrap:
    servers: ${LOCAL_BROKER}

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO

mp:
  messaging:
    incoming:
      created:
        connector: smallrye-kafka
        topic: "item-created"
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      updated:
        connector: smallrye-kafka
        topic: "item-updated"
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      deleted:
        connector: smallrye-kafka
        topic: "item-deleted"
        value:
         deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    outgoing:
 #     priority:
  #      connector: smallrye-kafka
   #     topic: "feedback-priority"
    #    value:
     #     serializer: org.apache.kafka.common.serialization.StringSerializer
 #     completed:
  #      connector: smallrye-kafka
   #     topic: "feedback-completed"
    #    value:
     #     serializer: org.apache.kafka.common.serialization.StringSerializer
